### ISSUE TITLE
common/stream.js: TypeError: Cannot read properties of null (reading 'set')

### ISSUE THREAD

**Issue by mistakia** [mistakia/nano-node-light#16]
```
file:///Users/trashman/Projects/nano-node-light/common/stream.js:76
  state.body.set(body, state.bodySize)
             ^

TypeError: Cannot read properties of null (reading 'set')
    at NanoStream.streamPacketBody (file:///Users/trashman/Projects/nano-node-light/common/stream.js:76:14)
    at NanoStream.streamPacket (file:///Users/trashman/Projects/nano-node-light/common/stream.js:99:10)
    at NanoStream.process (file:///Users/trashman/Projects/nano-node-light/common/stream.js:144:25)
    at NanoStream.push (file:///Users/trashman/Projects/nano-node-light/common/stream.js:163:12)
    at Socket.<anonymous> (file:///Users/trashman/Projects/nano-node-light/lib/nano-socket.js:41:45)
```

**Comment by NoSecretImprove** [comment]
^ Still under investigation by me and mistakia
